/*
List all genres of the show Dexter.
*/
SELECT TV_GENRES.NAME
FROM TV_SHOWS
JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.TV_SHOW_ID
JOIN TV_GENRES ON TV_SHOW_GENRES.TV_GENRE_ID = TV_GENRES.ID
WHERE TV_SHOWS.TITLE = 'Dexter'
ORDER BY TV_GENRES.NAME ASC;
