/*
List all Comedy shows in the database hbtn_0d_tvshows.
*/
SELECT TV_SHOWS.TITLE
FROM TV_SHOWS
JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.TV_SHOW_ID
JOIN TV_GENRES ON TV_SHOW_GENRES.TV_GENRE_ID = TV_GENRES.ID
WHERE TV_GENRES.NAME = 'Comedy'
ORDER BY TV_SHOWS.TITLE ASC;
